Repository yeti-platform/yeti, pull requests merged in 2023-11, with the labels that each got.

#882 Add user agent observable type, closes #869
  core/schemas/observable.py
  core/schemas/observables/user_agent.py
  tests/schemas/observable.py
Labels: enhancement

#884 Feat: Take type parameter into account when matching observables, closes #880, closes #885
  core/schemas/observable.py
  core/schemas/observables/generic_observable.py
  core/web/apiv2/graph.py
  tests/apiv2/graph.py
  tests/schemas/observable.py
Labels: bug, enhancement, breaking

#898 Fix: Update docker documentation with pointers to official docs
  extras/docker/README.md
Labels: docker

#897 Fix: Nicer error message when attempting to tag unsaved items
  core/database_arango.py
  tests/schemas/tag.py
Labels: minor

#899 Fix: sort only if there is something to sort
  core/database_arango.py
Labels: bug

#900 fix: add_type is optional
  core/web/apiv2/graph.py
Labels: bug

#906 Implement plugins loader to automagically add new ones
  core/taskmanager.py
  core/taskscheduler.py
  core/web/apiv2/system.py
  core/web/apiv2/tasks.py
  extras/docker/docker-entrypoint.sh
  tests/apiv2/tasks.py
  yeti.conf.sample
Labels: enhancement
