Repository yeti-platform/yeti, pull requests merged in 2023-12, with the labels that each got.

#926 Fix: Poetry install with --no-root
  .github/workflows/docker-build.yml
  .github/workflows/docker-publish.yml
  .github/workflows/unittests.yml
  extras/docker/Dockerfile
  extras/docker/dev/Dockerfile
Labels: code health

#942 Feed bugs
  plugins/feeds/public/hybrid_analysis.py
  plugins/feeds/public/vxvault_url.py
  tests/feeds.py
Labels: bug, tasks:feed

#954 Fix: calling save() doesn't overwrite all the object's contents (fixes #947)
  core/database_arango.py
  tests/schemas/observable.py
Labels: bug

#958 Fix: Add netloc to redirect after OIDC auth
  core/web/apiv2/auth.py
  yeti.conf.sample
Labels: bug

#957 Implement user account observable
  core/schemas/observable.py
  core/schemas/observables/user_account.py
  tests/schemas/observable.py
Labels: feature-request

#960 Feat: Auditability (Closes #916)
  .github/workflows/unittests.yml
  core/logger.py
  core/schemas/audit.py
  core/web/apiv2/auth.py
  core/web/apiv2/system.py
  core/web/webapp.py
  tests/apiv2/entities.py
  tests/apiv2/graph.py
  tests/apiv2/indicators.py
  tests/apiv2/observables.py
  tests/apiv2/tags.py
  tests/apiv2/tasks.py
  tests/apiv2/templates.py
  tests/apiv2/users.py
  yeti.conf.sample
Labels: enhancement, breaking

#962 Feat: More structured response when calling bulk_add
  core/schemas/observable.py
  core/web/apiv2/observables.py
  tests/apiv2/auth.py
  tests/apiv2/observables.py
Labels: breaking, code health

#971 Fix: error when forcing type to "guess"
  core/web/apiv2/graph.py
  tests/apiv2/auth.py
  tests/apiv2/graph.py
  yeti.conf.sample
Labels: bug
