Repository yeti-platform/yeti, pull requests merged in 2024-01, with the labels that each got.

#972 Fix: pydantic warning by replacing gte/lte with ge/le
  core/schemas/entity.py
Labels: bug

#974 Fix: API key save when creating new user
  yetictl/cli.py
Labels: bug

#983 Fix: Change endpoints to avoid redirect
  tests/apiv2/templates.py
  tests/apiv2/users.py
Labels: bug

#988 Add support for running Censys queries via analytics
  core/schemas/indicator.py
  plugins/analytics/public/censys.py
  poetry.lock
  pyproject.toml
  tests/analytics_test.py
Labels: tasks:feed

#1000 Feat: Reintroduce Expire Tags analytics
  core/database_arango.py
  core/schemas/graph.py
  plugins/analytics/public/expire_tags.py
  tests/analytics_test.py
  tests/schemas/tag.py
Labels: bug, tasks:analytics

#996 Add Wiz Threat Landscape feed
  plugins/feeds/public/wiz_cloud_threat_landscape.py
Labels: tasks:feed
