Repository yeti-platform/yeti, pull requests merged in 2024-03, with the labels that each got.

#1031 Add API endpoints to swap links
  core/database_arango.py
  core/interfaces.py
  core/web/apiv2/graph.py
  tests/apiv2/graph.py
Labels: enhancement

#1052 Fix normalization
  core/schemas/tag.py
Labels: bug

#1029 Change tor_exit_nodes feed to use the Tor Onionoo API + introduce tests
  plugins/feeds/public/tor_exit_nodes.py
  tests/analytics_test.py
  tests/feeds.py
  tests/helpers.py
  tests/tor_exit_nodes_test.py
Labels: tasks:feed

#1056 Tweak feed actions
  .github/workflows/feedtest.yml
  extras/docker/dev/docker-compose.yaml
  poetry.lock
  pyproject.toml
Labels: tasks:feed

#1059 Add logout actions and session store (fixes #1041, fixes #1022)
  core/web/apiv2/auth.py
  tests/apiv2/auth.py
Labels: bug, noteworthy
