Repository yeti-platform/yeti, pull requests merged in 2024-12, with the labels that each got.

#1202 Add progress bar for long running migrations
  core/migrations/arangodb.py
  poetry.lock
  pyproject.toml
Labels: enhancement, code health, python, core

#1203 Move hostname_extract under events and fix validator call
  plugins/events/hostname_extract.py
Labels: enhancement, minor, python, tasks:event

#1205 Redirect to / on state mismatch instead of 500
  core/web/apiv2/auth.py
Labels: bug

#1206 Add validator to graph search
  core/web/apiv2/graph.py
Labels: code health

#1209 DFIQ fix
  core/database_arango.py
  core/schemas/dfiq.py
  plugins/feeds/public/dfiq.py
Labels: bug

#1211 Update modified timestamps on save (closes #1191)
  .github/workflows/feedtest.yml
  core/schemas/audit.py
  core/schemas/dfiq.py
  core/schemas/entity.py
  core/schemas/indicator.py
  core/schemas/observable.py
  core/web/apiv2/dfiq.py
Labels: enhancement
