Repository yeti-platform/yeti, pull requests merged in 2024-07, with the labels that each got.

#1098 Fix #1097
  core/schemas/observable.py
  tests/schemas/observable.py
Labels: bug

#1100 Fixes date parsing issue by setting date format
  plugins/feeds/public/viriback_tracker.py
Labels: bug, tasks:feed

#1102 Suricata Rules
  core/schemas/indicator.py
  poetry.lock
  pyproject.toml
Labels: enhancement, feature-request

#1105 Add ETOpen
  core/schemas/indicator.py
  plugins/feeds/public/et_open.py
  tests/feeds.py
  yeti.conf.sample
Labels: enhancement, tasks:feed

#1107 Add new dfiq_archive endpoint
  core/web/apiv2/dfiq.py
  tests/apiv2/dfiq.py
Labels: enhancement

#1106 Add test for multiple entity types
  tests/apiv2/entities.py
Labels: code health

#1111 Do not log contents of body for /user/ paths
  core/web/webapp.py
Labels: security-impact

#1112 Regex matching in /graph/match
  core/database_arango.py
  core/web/apiv2/graph.py
  tests/apiv2/graph.py
Labels: enhancement

#1114 Add the new `in` operator in neighbor filter
  core/database_arango.py
  tests/apiv2/graph.py
Labels: enhancement

#1116 Be more flexible when searching patterns
  core/database_arango.py
Labels: enhancement
