Repository yeti-platform/yeti, pull requests merged in 2024-02, with the labels that each got.

#994 Add support for running Shodan queries via analytics
  core/schemas/indicator.py
  plugins/analytics/public/censys.py
  plugins/analytics/public/shodan.py
  poetry.lock
  pyproject.toml
  tests/analytics_test.py
  yeti.conf.sample
Labels: tasks:analytics

#987 Feat: Support DFIQ objects
  core/database_arango.py
  core/schemas/dfiq.py
  core/web/apiv2/dfiq.py
  core/web/apiv2/graph.py
  core/web/webapp.py
  plugins/feeds/public/dfiq.py
  poetry.lock
  pyproject.toml
  tests/apiv2/dfiq.py
  tests/dfiq_test_data/F1005.yaml
  tests/dfiq_test_data/Q1020.10.yaml
  tests/dfiq_test_data/Q1020.yaml
  tests/dfiq_test_data/S1003.yaml
  tests/feeds.py
  tests/schemas/dfiq.py
  tests/schemas/fixture.py
Labels: enhancement

#1004 Bug fix in Shodan config + add a test for it
  plugins/analytics/public/shodan.py
  tests/analytics_test.py
Labels: bug

#990 Import Misp Json format
  core/common/misp_to_yeti.py
  core/schemas/observable.py
  core/schemas/observables/mutex.py
  core/schemas/observables/named_pipe.py
  core/web/apiv2/import_data.py
  core/web/webapp.py
  plugins/feeds/public/misp.py
  tests/apiv2/import_data.py
  tests/misp_test_data/misp_event.json
  tests/schemas/observable.py
Labels: tasks:feed

#1011 Bump fastapi to 109
  core/web/webapp.py
  poetry.lock
  pyproject.toml
Labels: code health

#1010 Introduce ForensicArtifacts indicator type
  core/schemas/dfiq.py
  core/schemas/indicator.py
  core/web/apiv2/dfiq.py
  core/web/apiv2/entities.py
  core/web/apiv2/indicators.py
  core/web/apiv2/observables.py
  core/web/apiv2/tasks.py
  core/web/apiv2/templates.py
  plugins/feeds/public/artifacts.py
  plugins/feeds/public/dfiq.py
  poetry.lock
  pyproject.toml
  tests/apiv2/indicators.py
  tests/feeds.py
  tests/schemas/indicator.py
Labels: enhancement

#1016 Use arbitrary str instead of enum for querytype
  core/schemas/indicator.py
  plugins/analytics/public/censys.py
  plugins/analytics/public/shodan.py
  plugins/feeds/public/dfiq.py
  tests/analytics_test.py
  tests/schemas/fixture.py
Labels: code health

#1018 Refactor the DFIQ import to import from local system as well
  core/schemas/dfiq.py
  extras/git/ruff-precommit-check.sh
  plugins/feeds/public/dfiq.py
  yeti.conf.sample
Labels: enhancement, tasks:feed

#1019 Introduce min / max hops to graph search
  .vscode/settings.json
  core/database_arango.py
  core/interfaces.py
  core/web/apiv2/graph.py
  tests/apiv2/entities.py
  tests/apiv2/graph.py
  tests/schemas/entity.py
Labels: enhancement

#1027 Excluding Comment Lines from phishing_database Feed
  plugins/feeds/public/phishing_database.py
Labels: bug, tasks:feed
