Repository yeti-platform/yeti, pull requests merged in 2024-04, with the labels that each got.

#1058 Fix OTX feed and tags for Mitre Attack
  plugins/feeds/public/attack.py
  plugins/feeds/public/otx_alienvault.py
  poetry.lock
  pyproject.toml
Labels: bug

#1061 new feed TweetLive
  plugins/feeds/public/tweetlive.py
  tests/feeds.py
Labels: tasks:feed

#1062 Strongly type GraphResponse
  core/web/apiv2/graph.py
  tests/apiv2/graph.py
Labels: bug

#1065 Graph search can now select target vertices based on root_type (previously only leaf types)
  core/database_arango.py
  tests/apiv2/graph.py
Labels: enhancement, noteworthy

#1066 Remove usage of deprecated traverse() function
  core/database_arango.py
  extras/docker/dev/docker-compose.yaml
  tests/apiv2/observables.py
Labels: code health
